package wssc.billing.database;

import wssc.objects.Account;
import wssc.objects.DBMSConnection;
import java.sql.*;
import java.util.*;
import javax.swing.table.*;
import javax.swing.*;

/**
 *
 * @author Dev
 */
public class WSSCCustomerAccounts extends javax.swing.JFrame {

    /**
     * Creates new form wsscCustomerAccountsFrame
     */
    public WSSCCustomerAccounts() {
        initComponents();
    }
    
    public ArrayList<Account> accountList(){
        ArrayList<Account> accountList = new ArrayList<>();
        
        try{
            DBMSConnection con = new DBMSConnection();
            Statement stmt = con.getConnection().createStatement();
            
            String query = "";
            String owner_name = "";
            
            boolean getName = true;

            //depending on radio button, retrieve specific list of accounts
            if(residentialOption.isSelected()){
                query = "select * from dsoe1db.WSSC_CUST_ACCT natural join dsoe1db.WSSC_RESIDENTIAL_CUST where ACCOUNT_ID = ACC_ID";
                
                owner_name = "FNAME";
            }
            else if(governmentOption.isSelected()){
                query = "select * from dsoe1db.WSSC_CUST_ACCT natural join dsoe1db.WSSC_GOVT_CUST where ACCOUNT_ID = ACC_ID";
                
                owner_name = "AGENCY_NAME";
            }
            else if(commercialOption.isSelected()){
                query = "select * from dsoe1db.WSSC_CUST_ACCT natural join dsoe1db.WSSC_COMMERCIAL_CUST where ACCOUNT_ID = ACC_ID";
                
                owner_name = "COMPANY_NAME";
                
            }
            else if (allOption.isSelected()){
                query = "select * from dsoe1db.WSSC_CUST_ACCT";
                getName = false;

            }
            else{
                JOptionPane.showMessageDialog(null, "Please choose an option.");
            }
            
            //Execute Query to database
            ResultSet rs = stmt.executeQuery(query);
            Account account;
            
            //insert account objects into arraylist, which will be used to populate jTable
            while(rs.next()){
                if (getName == true){
                    account = new Account(rs.getInt("ACCOUNT_ID"), rs.getInt("CREDIT_CARD_NO"), rs.getString(owner_name));
                }
                else {
                    account = new Account(rs.getInt("ACCOUNT_ID"), rs.getInt("CREDIT_CARD_NO"), "");
                }
                    
                accountList.add(account);
            }            
        }
        catch (SQLException e){
            System.err.println(e);
        }

        return accountList;
    }
    
    public void show_accounts(){
        ArrayList<Account> accountsList = accountList();
        DefaultTableModel model = (DefaultTableModel) Accounts_Table.getModel();
        
        model.setRowCount(0);
        
        Object[] row = new Object[3];
        
        for(int i = 0; i < accountsList.size(); i++){
            row[0] = accountsList.get(i).get_owner();
            row[1] = accountsList.get(i).get_user_id();
            row[2] = accountsList.get(i).get_credit_card();
            model.addRow(row);
        }
        
                    
        DefaultTableCellRenderer leftRenderer = new DefaultTableCellRenderer();
        leftRenderer.setHorizontalAlignment(JLabel.LEFT);
        
        for(int i = 0; i < accountsList.size(); i++){
            Accounts_Table.getColumnModel().getColumn(i).setCellRenderer(leftRenderer);
        }    
    }
    

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        custAcctSelection = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        commercialOption = new javax.swing.JRadioButton();
        governmentOption = new javax.swing.JRadioButton();
        mainMenuLabel = new javax.swing.JLabel();
        allOption = new javax.swing.JRadioButton();
        toMainMenu = new javax.swing.JButton();
        residentialOption = new javax.swing.JRadioButton();
        executeSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Accounts_Table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CUSTOMER ACCOUNTS");

        jPanel2.setBackground(new java.awt.Color(163, 223, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        custAcctSelection.add(commercialOption);
        commercialOption.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        commercialOption.setText("Commercial");
        commercialOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commercialOptionActionPerformed(evt);
            }
        });

        custAcctSelection.add(governmentOption);
        governmentOption.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        governmentOption.setText("Government");

        mainMenuLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        mainMenuLabel.setForeground(new java.awt.Color(102, 204, 255));
        mainMenuLabel.setText("Customer Accounts");

        custAcctSelection.add(allOption);
        allOption.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        allOption.setText("All");

        toMainMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        toMainMenu.setText("Back");
        toMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toMainMenuActionPerformed(evt);
            }
        });

        custAcctSelection.add(residentialOption);
        residentialOption.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        residentialOption.setText("Residential");

        executeSearch.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        executeSearch.setText("Search");
        executeSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(allOption, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(governmentOption)
                    .addComponent(residentialOption, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(commercialOption, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(executeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(toMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(mainMenuLabel))
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(mainMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(residentialOption)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(governmentOption)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(commercialOption)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(allOption)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(executeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toMainMenu))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {executeSearch, toMainMenu});

        Accounts_Table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Accounts_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Owner Name", "Account ID Number", "Credit Card Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Accounts_Table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Accounts_Table);
        if (Accounts_Table.getColumnModel().getColumnCount() > 0) {
            Accounts_Table.getColumnModel().getColumn(0).setResizable(false);
            Accounts_Table.getColumnModel().getColumn(1).setResizable(false);
            Accounts_Table.getColumnModel().getColumn(1).setPreferredWidth(10);
            Accounts_Table.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 934, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void commercialOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commercialOptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_commercialOptionActionPerformed
        
    private void toMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toMainMenuActionPerformed
        // TODO add your handling code here:
        dispose();
        MainMenuFrame main_menu = new MainMenuFrame();
        main_menu.show();
    }//GEN-LAST:event_toMainMenuActionPerformed

    private void executeSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeSearchActionPerformed
        // TODO add your handling code here:
        show_accounts();
    }//GEN-LAST:event_executeSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WSSCCustomerAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WSSCCustomerAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WSSCCustomerAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WSSCCustomerAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WSSCCustomerAccounts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Accounts_Table;
    private javax.swing.JRadioButton allOption;
    private javax.swing.JRadioButton commercialOption;
    private javax.swing.ButtonGroup custAcctSelection;
    private javax.swing.JButton executeSearch;
    private javax.swing.JRadioButton governmentOption;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mainMenuLabel;
    private javax.swing.JRadioButton residentialOption;
    private javax.swing.JButton toMainMenu;
    // End of variables declaration//GEN-END:variables
}
