package wssc.billing.database;

import wssc.objects.Employee;
import wssc.objects.DBMSConnection;
import java.util.*;
import javax.swing.*;
import java.sql.*;
import javax.swing.table.*;

public class WSSCEmployees extends javax.swing.JFrame {
    
    /**
     * Creates new form NewJFrame
     */
    public WSSCEmployees() {
        initComponents();
    }
    
    //create list of Employee Objects to display
    public ArrayList<Employee> employeeList(){
        ArrayList<Employee> employeeList = new ArrayList<>();
        
        try{
            Connection con = DBMSConnection.getConnection();
            Statement stmt = con.createStatement();
            
            String query = "";
            
            if(customerServiceOption.isSelected()){
                query = "SELECT * FROM dsoe1db.WSSC_EMPLOYEE WHERE EMPLOYEE_ID in "
                        + "(SELECT E_ID FROM dsoe1db.WSSC_SERVICE_REP)";
            }
            else if(billingSpecialistOption.isSelected()){
                query = "SELECT * FROM dsoe1db.WSSC_EMPLOYEE WHERE EMPLOYEE_ID in "
                        + "(SELECT E_ID FROM dsoe1db.WSSC_BILLING_SPECIALIST)";
            }
            else if(utilityOption.isSelected()){
                query = "SELECT * FROM dsoe1db.WSSC_EMPLOYEE WHERE EMPLOYEE_ID in "
                        + "(SELECT E_ID FROM dsoe1db.WSSC_UTILITY_WORKER)";
            }
            else if(permitOfficerOption.isSelected()){
                query = "SELECT * FROM dsoe1db.WSSC_EMPLOYEE WHERE EMPLOYEE_ID in "
                        + "(SELECT E_ID FROM dsoe1db.WSSC_PERMIT_OFFICER)";
            }
            else if(allOption.isSelected()){
                query = "SELECT * FROM dsoe1db.WSSC_EMPLOYEE";
            }
            else{
                JOptionPane.showMessageDialog(null, "Please choose an option.");
            }
            
            ResultSet rs = stmt.executeQuery(query);
            Employee employee;
            
            while(rs.next()){
                
                String name = rs.getString("FNAME") + " " + rs.getString("LNAME");               
                employee = new Employee(rs.getInt("EMPLOYEE_ID"), name, rs.getString("PHONE_NUM"), rs.getString("SEX"), rs.getInt("DNUM"), rs.getString("PASSWORD"));
                employeeList.add(employee);
                
            }
            
        }
        catch(SQLException e){
            System.err.println(e);
        }
        
        return employeeList;
    }
    
    public void showEmployees(){
        ArrayList<Employee> emps_list = employeeList();
        
        DefaultTableModel model = (DefaultTableModel) employeesTable.getModel();        
        model.setRowCount(0);
        Object[] row = new Object[5];
        
        for(int i = 0; i < emps_list.size(); i++){
            row[0] = emps_list.get(i).get_employee_id();
            row[1] = emps_list.get(i).get_name();
            row[2] = emps_list.get(i).get_phone_num();
            row[3] = emps_list.get(i).get_sex();
            row[4] = emps_list.get(i).get_dnum();
                    
            model.addRow(row);
        }
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        
        for(int i = 0; i < 5; i++){
            employeesTable.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
            
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        executeSearch = new javax.swing.JButton();
        customerServiceOption = new javax.swing.JRadioButton();
        permitOfficerOption = new javax.swing.JRadioButton();
        mainMenuLabel = new javax.swing.JLabel();
        allOption = new javax.swing.JRadioButton();
        toMainMenu = new javax.swing.JButton();
        billingSpecialistOption = new javax.swing.JRadioButton();
        utilityOption = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        employeesTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EMPLOYEES");

        jPanel2.setBackground(new java.awt.Color(163, 223, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        executeSearch.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        executeSearch.setText("Search");
        executeSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeSearchActionPerformed(evt);
            }
        });

        buttonGroup1.add(customerServiceOption);
        customerServiceOption.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        customerServiceOption.setText("Customer Service Representatives");
        customerServiceOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerServiceOptionActionPerformed(evt);
            }
        });

        buttonGroup1.add(permitOfficerOption);
        permitOfficerOption.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        permitOfficerOption.setText("Permit Officer");
        permitOfficerOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                permitOfficerOptionActionPerformed(evt);
            }
        });

        mainMenuLabel.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        mainMenuLabel.setForeground(new java.awt.Color(102, 204, 255));
        mainMenuLabel.setText("Employees");

        buttonGroup1.add(allOption);
        allOption.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        allOption.setText("All");
        allOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allOptionActionPerformed(evt);
            }
        });

        toMainMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        toMainMenu.setText("Back");
        toMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toMainMenuActionPerformed(evt);
            }
        });

        buttonGroup1.add(billingSpecialistOption);
        billingSpecialistOption.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        billingSpecialistOption.setText("Billing Specialists");
        billingSpecialistOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billingSpecialistOptionActionPerformed(evt);
            }
        });

        buttonGroup1.add(utilityOption);
        utilityOption.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        utilityOption.setText("Utility Worker");
        utilityOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utilityOptionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customerServiceOption, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(billingSpecialistOption, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allOption, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(utilityOption, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(executeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(toMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(permitOfficerOption, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(mainMenuLabel)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerServiceOption, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(billingSpecialistOption, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(utilityOption, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(permitOfficerOption, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(allOption, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(executeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        employeesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "Name", "Phone Number", "Sex", "DNumber"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        employeesTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(employeesTable);
        if (employeesTable.getColumnModel().getColumnCount() > 0) {
            employeesTable.getColumnModel().getColumn(0).setResizable(false);
            employeesTable.getColumnModel().getColumn(1).setResizable(false);
            employeesTable.getColumnModel().getColumn(2).setResizable(false);
            employeesTable.getColumnModel().getColumn(3).setResizable(false);
            employeesTable.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 955, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void utilityOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utilityOptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_utilityOptionActionPerformed

    private void customerServiceOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerServiceOptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerServiceOptionActionPerformed

    private void allOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allOptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allOptionActionPerformed

    private void billingSpecialistOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billingSpecialistOptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billingSpecialistOptionActionPerformed

    private void toMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toMainMenuActionPerformed
        // TODO add your handling code here:
        dispose();
        MainMenuFrame main_menu = new MainMenuFrame();
        main_menu.show();
    }//GEN-LAST:event_toMainMenuActionPerformed

    private void executeSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeSearchActionPerformed
        // TODO add your handling code here:
        showEmployees();
    }//GEN-LAST:event_executeSearchActionPerformed

    private void permitOfficerOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_permitOfficerOptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_permitOfficerOptionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WSSCEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WSSCEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WSSCEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WSSCEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WSSCEmployees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton allOption;
    private javax.swing.JRadioButton billingSpecialistOption;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton customerServiceOption;
    private javax.swing.JTable employeesTable;
    private javax.swing.JButton executeSearch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mainMenuLabel;
    private javax.swing.JRadioButton permitOfficerOption;
    private javax.swing.JButton toMainMenu;
    private javax.swing.JRadioButton utilityOption;
    // End of variables declaration//GEN-END:variables
}